import { EmptyPrereqs, EmptySpellArray, SetChoiceNode, SetSpecAutolearn, SetTalentNode, SpecTabs } from "../TalentTreeLoader"

export function ReloadShamanRestoTree() {
    let TAB: uint32 = SpecTabs.RSHA
    let CLASS = Class.SHAMAN

    QueryWorld(`delete from character_spec_autolearn where \`class\` = ${CLASS} and \`spec\` = ${TAB}`)
    SetSpecAutolearn(CLASS, TAB, 10, GetID(`Spell`, `dh-spells`, `sha-res-naturesblessing`))
    SetSpecAutolearn(CLASS, TAB, 20, GetID(`Spell`, `dh-spells`, `sha-res-acidwaters`))
    SetSpecAutolearn(CLASS, TAB, 20, GetID(`Spell`, `dh-spells`, `sha-res-earthsblessing`))
    SetSpecAutolearn(CLASS, TAB, 10, GetID(`Spell`, `dh-spells`, `sha-res-mastery`))

    QueryWorld(`Delete from forge_talents where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_prereq where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_ranks where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_unlearn where talentTabId = ${TAB}`)

    let Talent : uint32 = GetID(`Spell`, 'dh-spells', `sha-res-riptide`)
    SetTalentNode(Talent, TAB, 6, 1, 0, false, 2**(TAB-1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-healingrain`)
    SetTalentNode(Talent, TAB, 5, 2, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-riptide`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-greaterhealingwave`)
    SetTalentNode(Talent, TAB, 6, 2, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-riptide`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-earthshield`)
    SetTalentNode(Talent, TAB, 7, 2, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-riptide`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-acidrain`)
    SetTalentNode(Talent, TAB, 4, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-healingrain`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-overflowingshores`)
    SetTalentNode(Talent, TAB, 5, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-healingrain`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-tidalwaves`)
    SetTalentNode(Talent, TAB, 6, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-healingrain`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-greaterhealingwave`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-earthshield`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-torrent`)
    SetTalentNode(Talent, TAB, 7, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-earthshield`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-cultivatingearth`)
    SetTalentNode(Talent, TAB, 8, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-earthshield`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-astralalignment`)
    SetTalentNode(Talent, TAB, 3, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-acidrain`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-earthsempoweringpetrichor`)
    SetTalentNode(Talent, TAB, 4, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-acidrain`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-overflowingshores`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-farshores`)
    SetChoiceNode(Talent, TAB, 6, 4, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-res-flowofthetides`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-res-overflowingshores')]: 1,  [GetID('Spell', 'dh-spells', 'sha-res-tidalwaves')]: 1, [GetID('Spell', 'dh-spells', 'sha-res-torrent')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-wavespeakersblessing`)
    SetTalentNode(Talent, TAB, 8, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-torrent`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-cultivatingearth`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-undulation`)
    SetTalentNode(Talent, TAB, 9, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-cultivatingearth`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `sha-res-spitefulspirits`)
    SetTalentNode(Talent, TAB, 3, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-astralalignment`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-earthsempoweringpetrichor`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-tidebringerr1`)
    SetTalentNode(Talent, TAB, 4, 5, 8, true, 0, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-res-tidebringerr2`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-earthsempoweringpetrichor`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-revitalizingtidetotem`)
    SetTalentNode(Talent, TAB, 6, 5, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-earthsempoweringpetrichor`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-farshores`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-wavespeakersblessing`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-flashfloodr1`)
    SetTalentNode(Talent, TAB, 8, 5, 8, true, 0, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-res-flashfloodr2`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-wavespeakersblessing`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-primaltidecore`)
    SetChoiceNode(Talent, TAB, 9, 5, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-res-hightide`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-res-wavespeakersblessing')]: 1,  [GetID('Spell', 'dh-spells', 'sha-res-undulation')]: 1}), EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-firesvitalembers`)
    SetTalentNode(Talent, TAB, 3, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-spitefulspirits`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-glacialrejuvenation`)
    SetTalentNode(Talent, TAB, 4, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-spitefulspirits`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-tidebringerr1`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-ancestralwaters`)
    SetChoiceNode(Talent, TAB, 5, 6, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-res-electrolyticwaters`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-res-revitalizingtidetotem')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-resurgence`)
    SetTalentNode(Talent, TAB, 6, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-revitalizingtidetotem`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-steadycurrent`)
    SetChoiceNode(Talent, TAB, 7, 6, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-res-currentcontrol`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-res-revitalizingtidetotem')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-wellspring`)
    SetTalentNode(Talent, TAB, 8, 6, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-flashfloodr1`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-primaltidecore`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-firesprotectiveembrance`)
    SetTalentNode(Talent, TAB, 9, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-primaltidecore`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-primordialwave`)
    SetTalentNode(Talent, TAB, 3, 7, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-firesvitalembers`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-glacialrejuvenation`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-spiritlink`)
    SetTalentNode(Talent, TAB, 4, 7, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-glacialrejuvenation`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-ancestralwaters`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-airsinvigoratingmist`)
    SetTalentNode(Talent, TAB, 6, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-ancestralwaters`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-resurgence`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-steadycurrent`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-cloudbursttotem`)
    SetTalentNode(Talent, TAB, 8, 7, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-steadycurrent`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-wellspring`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-res-improvedearthlivingweapon`)
    SetTalentNode(Talent, TAB, 9, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-res-wellspring`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-res-firesprotectiveembrance`)]: 1}), EmptySpellArray, EmptySpellArray)
}
