import { EmptyPrereqs, EmptySpellArray, SetChoiceNode, SetSpecAutolearn, SetTalentNode, SpecTabs } from "../TalentTreeLoader"

export function ReloadShamanTree() {
    let TAB: uint32 = 57

    QueryWorld(`Delete from forge_talents where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_prereq where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_ranks where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_unlearn where talentTabId = ${TAB}`)

    let Talent : uint32 = GetID(`Spell`, 'dh-spells', `sha-gen-chainheal`)
    SetTalentNode(Talent, TAB, 3, 1, 0, false, 2**(SpecTabs.RSHA-1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-astralshift`)
    SetTalentNode(Talent, TAB, 5, 1, 0, false, 2**(SpecTabs.WARD-1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-lavaburst`)
    SetTalentNode(Talent, TAB, 7, 1, 0, false, 2**(SpecTabs.ENHA-1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-chainlightning`)
    SetTalentNode(Talent, TAB, 9, 1, 0, false, 2**(SpecTabs.ELEM-1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-waterscalmingpresence`)
    SetTalentNode(Talent, TAB, 3, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-chainheal`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-brimmingwithlife`)
    SetTalentNode(Talent, TAB, 4, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-chainheal`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-astralshift`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-planestraveller`)
    SetChoiceNode(Talent, TAB, 5, 2, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-gen-astralbulwark`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-gen-astralshift')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-flameandice`)
    SetTalentNode(Talent, TAB, 7, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-lavaburst`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-reverberation`)
    SetTalentNode(Talent, TAB, 8, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-lavaburst`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-chainlightning`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-maelstromweapon`)
    SetTalentNode(Talent, TAB, 9, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-chainlightning`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-earthsdefense`)
    SetTalentNode(Talent, TAB, 4, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-waterscalmingpresence`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-brimmingwithlife`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-planestraveller`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-naturesfury`)
    SetTalentNode(Talent, TAB, 6, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-planestraveller`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-flameandice`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-electrifiedpurge`)
    SetChoiceNode(Talent, TAB, 8, 3, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-gen-greaterpurge`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-gen-flameandice')]: 1, [GetID('Spell', 'dh-spells', 'sha-gen-reverberation')]: 1, [GetID('Spell', 'dh-spells', 'sha-gen-maelstromweapon')]: 1}), EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-elementalfocus`)
    SetTalentNode(Talent, TAB, 3, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-earthsdefense`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-elementalwarding`)
    SetTalentNode(Talent, TAB, 5, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-planestraveller`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-earthsdefense`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-airscelerity`)
    SetTalentNode(Talent, TAB, 7, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-electrifiedpurge`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-flameandice`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-flurry`)
    SetTalentNode(Talent, TAB, 9, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-electrifiedpurge`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-elementalorbit`)
    SetTalentNode(Talent, TAB, 4, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-elementalfocus`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-elementalwarding`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-thunderstorm`)
    SetTalentNode(Talent, TAB, 6, 5, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-elementalwarding`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-naturesfury`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-airscelerity`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-gustofwind`)
    SetChoiceNode(Talent, TAB, 8, 5, 8, false, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-gen-spiritwalk`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-gen-airscelerity')]: 1, [GetID('Spell', 'dh-spells', 'sha-gen-flurry')]: 1}), EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-firespasion`)
    SetTalentNode(Talent, TAB, 3, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-elementalorbit`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-overflowingwell`)
    SetTalentNode(Talent, TAB, 4, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-elementalorbit`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-surgingshields`)
    SetTalentNode(Talent, TAB, 5, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-elementalorbit`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-thunderstorm`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-shockingimpact`)
    SetChoiceNode(Talent, TAB, 6, 6, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-gen-boomingdismissal`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-gen-thunderstorm')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-spiritwolf`)
    SetChoiceNode(Talent, TAB, 7, 6, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-gen-thunderouspaws`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'sha-gen-thunderstorm')]: 1, [GetID('Spell', 'dh-spells', 'sha-gen-gustofwind')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-gowiththeflow`)
    SetTalentNode(Talent, TAB, 8, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-gustofwind`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-totemicfocus`)
    SetTalentNode(Talent, TAB, 9, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-gustofwind`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-spiritwalkersswiftness`)
    SetTalentNode(Talent, TAB, 3, 7, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-firespasion`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-aidfrombeyond`)
    SetTalentNode(Talent, TAB, 4, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-firespasion`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-overflowingwell`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-surgingshields`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-staticshock`)
    SetTalentNode(Talent, TAB, 5, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-surgingshields`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-shockingimpact`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-unrelentingstormr1`)
    SetTalentNode(Talent, TAB, 6, 7, 8, true, 0, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `sha-gen-unrelentingstormr2`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-shockingimpact`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-sineater`)
    SetTalentNode(Talent, TAB, 7, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-shockingimpact`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-spiritwolf`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-windrush`)
    SetTalentNode(Talent, TAB, 8, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-spiritwolf`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-gowiththeflow`)]: 1, [GetID(`Spell`, `dh-spells`, `sha-gen-totemicfocus`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `sha-gen-totemsofwar`)
    SetTalentNode(Talent, TAB, 9, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `sha-gen-totemicfocus`)]: 1}), EmptySpellArray, EmptySpellArray)
}
