import { EmptyPrereqs, EmptySpellArray, SetChoiceNode, SetTalentNode, SpecTabs } from "../TalentTreeLoader"

export function ReloadWarlockTree() {
    let TAB: uint32 = 59

    QueryWorld(`Delete from forge_talents where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_prereq where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_ranks where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_unlearn where talentTabId = ${TAB}`)

    let Talent : uint32 = GetID(`Spell`, `dh-spells`, `warl-gen-feldomination`)
    SetTalentNode(Talent, TAB, 4, 1, 0, false, 2**(SpecTabs.DEMO - 1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-mortalcoil`)
    SetTalentNode(Talent, TAB, 6, 1, 0, false, 2**(SpecTabs.ALCK - 1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-shadowfury`)
    SetTalentNode(Talent, TAB, 8, 1, 0, false, 2**(SpecTabs.DEST - 1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-felsynergy`)
    SetTalentNode(Talent, TAB, 3, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-feldomination`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-demonskin`)
    SetTalentNode(Talent, TAB, 5, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-feldomination`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-mortalcoil`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-horrify`)
    SetChoiceNode(Talent, TAB, 7, 2, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `warl-gen-nightmare`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'warl-gen-mortalcoil')]: 1, [GetID('Spell', 'dh-spells', 'warl-gen-shadowfury')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-darkfury`)
    SetTalentNode(Talent, TAB, 9, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-shadowfury`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-manafeed`)
    SetTalentNode(Talent, TAB, 4, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-felsynergy`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-feldomination`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-demonskin`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = 48018
    SetTalentNode(Talent, TAB, 6, 3, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-demonskin`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-mortalcoil`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-horrify`)]: 1}), EmptySpellArray, CreateArray<uint32>([48020]))
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-knowledgeofthegreatbeyond`)
    SetTalentNode(Talent, TAB, 8, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-horrify`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-shadowfury`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-darkfury`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-demonicfortitude`)
    SetTalentNode(Talent, TAB, 3, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-manafeed`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-curseofelements`)
    SetChoiceNode(Talent, TAB, 5, 4, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `warl-gen-curseofweakness`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-manafeed`)]: 1, [48018]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-abysswalker`)
    SetTalentNode(Talent, TAB, 6, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[48018]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-empoweredsoulleech`)
    SetTalentNode(Talent, TAB, 7, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[48018]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-knowledgeofthegreatbeyond`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-demonicembrance`)
    SetTalentNode(Talent, TAB, 9, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-knowledgeofthegreatbeyond`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-felpact`)
    SetTalentNode(Talent, TAB, 4, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-demonicfortitude`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-manafeed`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-curseofelements`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-satyriccursesr1`)
    SetTalentNode(Talent, TAB, 5, 5, 8, true, 0, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `warl-gen-satyriccursesr2`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-curseofelements`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-soulsculptor`)
    SetTalentNode(Talent, TAB, 6, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-curseofelements`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-abysswalker`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-empoweredsoulleech`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-darkspellcasterr1`)
    SetTalentNode(Talent, TAB, 7, 5, 8, true, 0, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `warl-gen-darkspellcasterr2`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-empoweredsoulleech`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-learnedspellcaster`)
    SetTalentNode(Talent, TAB, 8, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-empoweredsoulleech`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-knowledgeofthegreatbeyond`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-demonicembrance`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-demonicresilience`)
    SetTalentNode(Talent, TAB, 3, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-felpact`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-felregeneration`)
    SetChoiceNode(Talent, TAB, 5, 6, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `warl-gen-felresistance`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-felpact`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-satyriccursesr1`)]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-ruin`)
    SetTalentNode(Talent, TAB, 6, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-satyriccursesr1`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-soulsculptor`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-darkspellcasterr1`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-spellstone`)
    SetChoiceNode(Talent, TAB, 7, 6, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `warl-gen-firestone`)]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-darkspellcasterr1`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-learnedspellcaster`)]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-lifeblood`)
    SetTalentNode(Talent, TAB, 9, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-learnedspellcaster`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-demonictactics`)
    SetTalentNode(Talent, TAB, 3, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-demonicresilience`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-demonicinspiration`)
    SetTalentNode(Talent, TAB, 4, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-demonicresilience`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-felpact`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-felregeneration`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-darkpact`)
    SetTalentNode(Talent, TAB, 6, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-felregeneration`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-ruin`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-spellstone`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-masterofthedarkarts`)
    SetTalentNode(Talent, TAB, 8, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-spellstone`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-learnedspellcaster`)]: 1, [GetID(`Spell`, `dh-spells`, `warl-gen-lifeblood`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `warl-gen-sweetsouls`)
    SetTalentNode(Talent, TAB, 9, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `warl-gen-lifeblood`)]: 1}), EmptySpellArray, EmptySpellArray)
}