import { EmptyPrereqs, EmptySpellArray, SetChoiceNode, SetTalentNode, SpecTabs } from "../TalentTreeLoader"

export function ReloadMageTree() {
    let TAB: uint32 = 58
    let ALLMASK = (2**(SpecTabs.FIRE - 1)) + (2**(SpecTabs.ARCA - 1)) + (2**(SpecTabs.FROS - 1))

    QueryWorld(`Delete from forge_talents where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_prereq where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_ranks where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_unlearn where talentTabId = ${TAB}`)

    let Talent : uint32 = GetID(`Spell`, 'dh-spells', `mag-gen-barrierarcana`)
    SetTalentNode(Talent, TAB, 6, 1, 0, false, ALLMASK, CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-frictionbarrier`)
    SetTalentNode(Talent, TAB, 5, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-barrierarcana`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-manabarrier`)
    SetTalentNode(Talent, TAB, 6, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-barrierarcana`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-coldwinds`)
    SetTalentNode(Talent, TAB, 7, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-barrierarcana`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-magicabsorption`)
    SetTalentNode(Talent, TAB, 5, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-frictionbarrier`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-incantersabsorption`)
    SetTalentNode(Talent, TAB, 6, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-frictionbarrier`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-manabarrier`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-coldwinds`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-fadingbarriers`)
    SetTalentNode(Talent, TAB, 7, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-coldwinds`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-blastwave`)
    SetTalentNode(Talent, TAB, 4, 4, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-magicabsorption`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-moltenarmor`)
    SetChoiceNode(Talent, TAB, 6, 4, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `mag-gen-frostarmor`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'mag-gen-magicabsorption')]: 1, [GetID('Spell', 'dh-spells', 'mag-gen-incantersabsorption')]: 1, [GetID('Spell', 'dh-spells', 'mag-gen-fadingbarriers')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-iceblock`)
    SetTalentNode(Talent, TAB, 8, 4, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-fadingbarriers`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-heatwave`)
    SetTalentNode(Talent, TAB, 3, 5, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-blastwave`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-childsplay`)
    SetTalentNode(Talent, TAB, 5, 5, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-blastwave`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-magicabsorption`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-moltenarmor`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = 55342
    SetTalentNode(Talent, TAB, 6, 5, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-moltenarmor`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-etherealfocus`)
    SetTalentNode(Talent, TAB, 7, 5, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-moltenarmor`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-fadingbarriers`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-iceblock`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-cryofreeze`)
    SetTalentNode(Talent, TAB, 9, 5, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-iceblock`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-pridefulfirebrand`)
    SetTalentNode(Talent, TAB, 3, 6, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-heatwave`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-intensefocus`)
    SetTalentNode(Talent, TAB, 4, 6, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-heatwave`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-blastwave`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-childsplay`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-bookworm`)
    SetTalentNode(Talent, TAB, 5, 6, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-childsplay`)]: 1, [55342]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-fivesaparty`)
    SetChoiceNode(Talent, TAB, 6, 6, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `mag-gen-reduplication`)]), CreateDictionary<uint32, uint8>({[55342]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-magicaltiming`)
    SetTalentNode(Talent, TAB, 7, 6, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[55342]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-etherealfocus`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-pristinemanagem`)
    SetTalentNode(Talent, TAB, 8, 6, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-etherealfocus`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-iceblock`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-cryofreeze`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-chillydisposition`)
    SetTalentNode(Talent, TAB, 9, 6, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-cryofreeze`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-burningresolve`)
    SetTalentNode(Talent, TAB, 3, 7, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-pridefulfirebrand`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-intensefocus`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-magicansflourish`)
    SetTalentNode(Talent, TAB, 4, 7, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-intensefocus`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-bookworm`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-timetopanic`)
    SetTalentNode(Talent, TAB, 5, 7, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-bookworm`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-displacement`)
    SetTalentNode(Talent, TAB, 6, 7, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-bookworm`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-fivesaparty`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-magicaltiming`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-shimmer`)
    SetTalentNode(Talent, TAB, 7, 7, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-magicaltiming`)]: 1}), CreateArray<uint32>([GetID(`Spell`, `dh-spells`, `mag-gen-blink`)]), CreateArray<uint32>([GetID(`Spell`, `dh-spells`, `mag-gen-shimmerblink`)]))
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-tormentor`)
    SetTalentNode(Talent, TAB, 8, 7, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-magicaltiming`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-pristinemanagem`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `mag-gen-rigidice`)
    SetTalentNode(Talent, TAB, 9, 7, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `mag-gen-pristinemanagem`)]: 1, [GetID(`Spell`, `dh-spells`, `mag-gen-chillydisposition`)]: 1}), EmptySpellArray, EmptySpellArray)
}
