import { EmptyPrereqs, EmptySpellArray, SetChoiceNode, SetTalentNode, SpecTabs } from "../TalentTreeLoader"

export function ReloadPriestTree() {
    let TAB: uint32 = 55
    let ALLMASK = (2**(SpecTabs.HPRI - 1)) + (2**(SpecTabs.DISC - 1)) + (2**(SpecTabs.SPRI - 1)) + (2**(SpecTabs.INQU - 1))
    let HOLYDISC = (2**(SpecTabs.HPRI - 1)) + (2**(SpecTabs.DISC - 1))
    let HOLYINQ = (2**(SpecTabs.HPRI - 1)) + (2**(SpecTabs.INQU - 1))
    let SHADISC = (2**(SpecTabs.DISC - 1)) + (2**(SpecTabs.SPRI - 1))

    QueryWorld(`Delete from forge_talents where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_prereq where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_ranks where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_unlearn where talentTabId = ${TAB}`)

    let Talent : uint32 = GetID(`Spell`, 'dh-spells', `pri-gen-prayerofmending`)
    SetTalentNode(Talent, TAB, 4, 1, 0, false, HOLYDISC, CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-purify`)
    SetTalentNode(Talent, TAB, 5, 1, 0, false, ALLMASK, CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-holynova`)
    SetTalentNode(Talent, TAB, 7, 1, 0, false, HOLYINQ, CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-shadowworddeath`)
    SetTalentNode(Talent, TAB, 8, 1, 0, false, SHADISC, CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-focusedmending`)
    SetTalentNode(Talent, TAB, 3, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-prayerofmending`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-shackleevil`)
    SetTalentNode(Talent, TAB, 4, 2, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-prayerofmending`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-purify`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-soultap`)
    SetTalentNode(Talent, TAB, 5, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-purify`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-leapoffaithdummy`)
    SetTalentNode(Talent, TAB, 6, 2, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-purify`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-holynova`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-rhapsody`)
    SetTalentNode(Talent, TAB, 7, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-holynova`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-twilightfiend`)
    SetTalentNode(Talent, TAB, 8, 2, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-holynova`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-shadowworddeath`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-deathandmadness`)
    SetTalentNode(Talent, TAB, 9, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-shadowworddeath`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-lightresonance`)
    SetTalentNode(Talent, TAB, 3, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-focusedmending`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-inquisitorscell`)
    SetTalentNode(Talent, TAB, 4, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-shackleevil`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-silence`)
    SetTalentNode(Talent, TAB, 5, 3, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-shackleevil`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-soultap`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-leapoffaithdummy`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-movewithgrace`)
    SetTalentNode(Talent, TAB, 6, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-leapoffaithdummy`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-resplendentlight`)
    SetTalentNode(Talent, TAB, 7, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-rhapsody`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `pri-gen-empoweredaberration`)
    SetChoiceNode(Talent, TAB, 8, 3, 0, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `pri-gen-agressiveaberration`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'pri-gen-twilightfiend')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-tithe`)
    SetTalentNode(Talent, TAB, 9, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-deathandmadness`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-efficientholycasting`)
    SetTalentNode(Talent, TAB, 4, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-lightresonance`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-inquisitorscell`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-silence`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-massdispel`)
    SetTalentNode(Talent, TAB, 6, 4, 0, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-silence`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-movewithgrace`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-resplendentlight`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-darkdevotion`)
    SetTalentNode(Talent, TAB, 8, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-resplendentlight`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-empoweredaberration`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-tithe`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-wordsofthepious`)
    SetTalentNode(Talent, TAB, 3, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-lightresonance`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-efficientholycasting`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-reflectinglight`)
    SetTalentNode(Talent, TAB, 4, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-efficientholycasting`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `pri-gen-empowereddispel`)
    SetChoiceNode(Talent, TAB, 5, 5, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, `dh-spells`, `pri-gen-takefromevil`)]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'pri-gen-efficientholycasting')]: 1, [GetID('Spell', 'dh-spells', 'pri-gen-silence')]: 1, [GetID('Spell', 'dh-spells', 'pri-gen-massdispel')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-angelicfeathers`)
    SetTalentNode(Talent, TAB, 6, 5, 8, false, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-massdispel`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-unbreakablewill`)
    SetTalentNode(Talent, TAB, 7, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-massdispel`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-resplendentlight`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-darkdevotion`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-phantasm`)
    SetTalentNode(Talent, TAB, 8, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-darkdevotion`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-vampiricembrance`)
    SetTalentNode(Talent, TAB, 9, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-darkdevotion`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-tithe`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-penitenceofthedamned`)
    SetTalentNode(Talent, TAB, 3, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-wordsofthepious`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-reflectinglight`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-blessedrecovery`)
    SetTalentNode(Talent, TAB, 4, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-reflectinglight`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-empowereddispel`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-kindledfaith`)
    SetTalentNode(Talent, TAB, 5, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-empowereddispel`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-angelicfeathers`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-giveflight`)
    SetTalentNode(Talent, TAB, 6, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-angelicfeathers`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-twistoffate`)
    SetTalentNode(Talent, TAB, 7, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-angelicfeathers`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-unbreakablewill`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-fading`)
    SetTalentNode(Talent, TAB, 8, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-unbreakablewill`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-phantasm`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-embracevampirism`)
    SetTalentNode(Talent, TAB, 9, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-vampiricembrance`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-sharingthelove`)
    SetTalentNode(Talent, TAB, 3, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-penitenceofthedamned`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-blessedrecovery`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-fanaticism`)
    SetTalentNode(Talent, TAB, 4, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-blessedrecovery`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-unwaveringwill`)
    SetTalentNode(Talent, TAB, 5, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-blessedrecovery`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-kindledfaith`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-pathofthedevout`)
    SetTalentNode(Talent, TAB, 6, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-kindledfaith`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-giveflight`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-twistoffate`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-phantasmalmutterings`)
    SetTalentNode(Talent, TAB, 7, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-twistoffate`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-fading`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-elunesgrace`)
    SetTalentNode(Talent, TAB, 8, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-fading`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', `pri-gen-darkexchange`)
    SetTalentNode(Talent, TAB, 9, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `pri-gen-fading`)]: 1, [GetID(`Spell`, `dh-spells`, `pri-gen-embracevampirism`)]: 1}), EmptySpellArray, EmptySpellArray)
    
}
