import { EmptyPrereqs, EmptySpellArray, SetChoiceNode, SetSpecAutolearn, SetTalentNode, SpecTabs } from "../TalentTreeLoader"

export function ReloadRogueAssTree() {
    let TAB: uint32 = SpecTabs.ASSR
    let CLASS = Class.ROGUE

    QueryWorld(`delete from character_spec_autolearn where \`class\` = ${CLASS} and \`spec\` = ${TAB}`)
    SetSpecAutolearn(CLASS, TAB, 10, GetID(`Spell`, 'dh-spells', 'rog-ass-excruciatingpoison'))
    SetSpecAutolearn(CLASS, TAB, 10, GetID(`Spell`, 'dh-spells', 'rog-ass-mutilate'))
    SetSpecAutolearn(CLASS, TAB, 10, GetID(`Spell`, 'dh-spells', 'rog-ass-envenom'))

    QueryWorld(`Delete from forge_talents where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_prereq where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_ranks where talentTabId = ${TAB}`)
    QueryWorld(`Delete from forge_talent_unlearn where talentTabId = ${TAB}`)

    let Talent : uint32 = GetID(`Spell`, 'dh-spells', 'rog-ass-poisonbomb')
    SetTalentNode(Talent, TAB, 6, 1, 0, false, 2**(TAB-1), CreateArray<uint32>([Talent]), EmptyPrereqs, EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-deadlypoison`)
    SetTalentNode(Talent, TAB, 5, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-poisonbomb`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-sealfate`)
    SetTalentNode(Talent, TAB, 7, 2, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-poisonbomb`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-sadistvenom`)
    SetTalentNode(Talent, TAB, 5, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-deadlypoison`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-focusedattacks`)
    SetTalentNode(Talent, TAB, 7, 3, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-sealfate`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-deadlierpoison`)
    SetTalentNode(Talent, TAB, 4, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-sadistvenom`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-secretingredient`)
    SetTalentNode(Talent, TAB, 5, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-sadistvenom`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-venomousdagger`)
    SetTalentNode(Talent, TAB, 6, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-sadistvenom`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-poisonbomb`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-focusedattacks`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-paintitallred`)
    SetTalentNode(Talent, TAB, 7, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-focusedattacks`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, `dh-spells`, `rog-ass-hiddenblade`)
    SetTalentNode(Talent, TAB, 8, 4, 0, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-focusedattacks`)]: 1}), EmptySpellArray, EmptySpellArray)
    
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-pathofpoison1')
    SetTalentNode(Talent, TAB, 3, 5, 8, true, 0, CreateArray<uint32>([Talent, GetID(`Spell`, 'dh-spells', 'rog-ass-pathofpoison2')]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-deadlierpoison`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-lethaldose')
    SetTalentNode(Talent, TAB, 4, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-deadlierpoison`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-preciseinjection')
    SetTalentNode(Talent, TAB, 5, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-deadlierpoison`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-secretingredient`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-cuttothechase')
    SetTalentNode(Talent, TAB, 6, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-paintitallred`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-venomousdagger`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-secretingredient`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-intenttokill')
    SetTalentNode(Talent, TAB, 7, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-paintitallred`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-hiddenblade`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-slicingmomentum')
    SetTalentNode(Talent, TAB, 8, 5, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-hiddenblade`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-pathofblood1')
    SetTalentNode(Talent, TAB, 9, 5, 8, true, 0, CreateArray<uint32>([Talent, GetID(`Spell`, 'dh-spells', 'rog-ass-pathofblood2')]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-hiddenblade`)]: 1}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-injectcatalyst')
    SetTalentNode(Talent, TAB, 3, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-pathofpoison1`)]: 2}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-wastenot')
    SetTalentNode(Talent, TAB, 4, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-preciseinjection`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-lethaldose`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-pathofpoison1`)]: 2}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-applytobloodstream')
    SetTalentNode(Talent, TAB, 5, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-preciseinjection`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-cuttothechase`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-indiscriminatecarnage')
    SetChoiceNode(Talent, TAB, 6, 6, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, 'dh-spells', 'rog-ass-wideslice')]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'rog-ass-cuttothechase')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-systemicfailure')
    SetTalentNode(Talent, TAB, 7, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-cuttothechase`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-intenttokill`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-exposedvein')
    SetTalentNode(Talent, TAB, 8, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-pathofblood1`)]: 2, [GetID(`Spell`, `dh-spells`, `rog-ass-slicingmomentum`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-intenttokill`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-whisperingdeath')
    SetTalentNode(Talent, TAB, 9, 6, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-pathofblood1`)]: 2}), EmptySpellArray, EmptySpellArray)

    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-coatedblade')
    SetTalentNode(Talent, TAB, 3, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-injectcatalyst`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-fasthands')
    SetTalentNode(Talent, TAB, 4, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-applytobloodstream`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-wastenot`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-injectcatalyst`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-viciousvenom')
    SetChoiceNode(Talent, TAB, 5, 7, 8, true, CreateArray<uint32>([Talent, GetID(`Spell`, 'dh-spells', 'rog-ass-dirtytricks')]), CreateDictionary<uint32, uint8>({[GetID('Spell', 'dh-spells', 'rog-ass-indiscriminatecarnage')]: 1, [GetID('Spell', 'dh-spells', 'rog-ass-applytobloodstream')]: 1}), EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-twisttheknife')
    SetTalentNode(Talent, TAB, 6, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-indiscriminatecarnage`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-doomblade')
    SetTalentNode(Talent, TAB, 7, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-indiscriminatecarnage`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-systemicfailure`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-exoticvenom')
    SetTalentNode(Talent, TAB, 8, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-whisperingdeath`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-exposedvein`)]: 1, [GetID(`Spell`, `dh-spells`, `rog-ass-systemicfailure`)]: 1}), EmptySpellArray, EmptySpellArray)
    Talent = GetID(`Spell`, 'dh-spells', 'rog-ass-sheaththeknife')
    SetTalentNode(Talent, TAB, 9, 7, 8, true, 0, CreateArray<uint32>([Talent]), CreateDictionary<uint32, uint8>({[GetID(`Spell`, `dh-spells`, `rog-ass-whisperingdeath`)]: 1}), EmptySpellArray, EmptySpellArray)

}